#!/bin/bash
find -type f -name "*.gif" \rev \ cut -d "/" -f 1 |[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[|[C[C[C[C[|[B[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D cut -d ':' -f 2- | rev | LC_ALL=C sort -f
